#!/usr/bin/env bash
#
# curl-auth.sh - hand the Qdrant API key to curl without putting it in argv.
#
# Sourced by install.sh, scripts/init-collections.sh and
# scripts/migrate-collection.sh. Defines functions and has no other effect when
# sourced, so it can also be sourced by a test.
#
# WHY THIS FILE EXISTS
#
#   curl -H "api-key: ${QDRANT_API_KEY}" "${QDRANT_URL}/readyz"
#
# puts the key into curl's argument vector, and argv is not private. Measured,
# not assumed - `ps -ww -eo pid=,command=` while one such poll was in flight
# printed, to any local process that cared to look:
#
#   58729 curl -s -o /dev/null -w %{http_code} --max-time 8 \
#         -H api-key: <the key, in clear> http://127.0.0.1:6363/readyz
#
# That is exactly the risk install.sh already refuses to take with
# `claude mcp add --env "QDRANT_API_KEY=..."`, and exactly the reason
# scripts/qdrant-mcp-launcher.sh exists at all. The same reasoning had simply
# never been carried across to curl, which made the two halves of this
# repository disagree with each other about the same threat.
#
# THE FIX
#
# Write the header into a curl configuration file created with mode 0600 and
# pass only its name with -K. A file name is not a credential, so argv stays
# clean, and the key is readable only by the user who is already able to read
# .env.
#
# Alternatives, and why -K won:
#
#   - An environment variable. curl has no "take this header from the
#     environment" option, so the value would have to be interpolated into an
#     argument anyway, which is the thing being avoided.
#   - `-H @file`. This does work - curl documents -H as <header/@file>, and a
#     --trace-ascii confirms the header is read from the file and sent - but it
#     was introduced in curl 7.55 (2017). An older curl has no @ handling for
#     -H and sends the literal string "@/tmp/thinktank-curlauth.XXXXXX" as the
#     header value, which fails as an authentication error rather than as
#     something recognisable. -K predates every curl anyone still runs, so it
#     cannot degrade that way. The price is the config-file quoting handled in
#     curl_auth_file_create below.
#
# The header from -K and any -H on the command line both apply, and -K composes
# with -d, -X and -w, so calls that already send a body need no restructuring.

# CURL_AUTH_FILE holds the path once curl_auth_file_create has run. It is a
# global on purpose: every caller needs it in every later curl invocation, and
# returning it through a command substitution would put the *file name* in a
# subshell while the trap that deletes it lives in the parent.
CURL_AUTH_FILE=""

# curl_auth_file_create KEY
#
# Creates the config file and sets CURL_AUTH_FILE. Returns 1 without leaving
# anything behind if the key is empty or the file cannot be written.
curl_auth_file_create() {
  local key="$1" f esc

  [ -n "${key}" ] || return 1

  f="$(mktemp "${TMPDIR:-/tmp}/thinktank-curlauth.XXXXXX")" || return 1
  # mktemp already creates the file 0600 on every platform this runs on. Doing
  # it again states the requirement instead of inheriting it, and costs one
  # syscall. It happens before the key is written, so there is no window in
  # which the file holds the key at a wider mode.
  if ! chmod 600 "${f}" 2>/dev/null; then
    rm -f "${f}"
    return 1
  fi

  # Inside a double-quoted value, a curl config file treats backslash and
  # double quote as escape characters. A key generated by `openssl rand -hex`
  # contains neither, but a key someone pasted into .env by hand can, and an
  # unescaped one would silently truncate the header or corrupt the line.
  esc="$(printf '%s' "${key}" | sed 's/[\\"]/\\&/g')"

  if ! printf 'header = "api-key: %s"\n' "${esc}" > "${f}"; then
    rm -f "${f}"
    return 1
  fi

  CURL_AUTH_FILE="${f}"
  return 0
}

# curl_auth_file_remove
#
# Deletes the file if it exists. Safe to call repeatedly and safe to call when
# nothing was ever created, because it is meant to run from a trap on EXIT, INT
# and TERM - the abort paths are the ones that would otherwise leave the key
# lying in the temp directory.
#
# The limit, stated rather than glossed over: SIGKILL cannot be trapped, so a
# `kill -9` (or a machine losing power) leaves the file behind. Observed once
# during testing, on a run killed while it was blocked in `docker compose up
# -d`. That is why the mode matters as much as the trap does - the file is 0600
# and readable only by the user who can already read .env. Stale files can be
# cleared with: rm -f "${TMPDIR:-/tmp}"/thinktank-curlauth.*
curl_auth_file_remove() {
  if [ -n "${CURL_AUTH_FILE:-}" ] && [ -f "${CURL_AUTH_FILE}" ]; then
    rm -f "${CURL_AUTH_FILE}"
  fi
  CURL_AUTH_FILE=""
  return 0
}
